<?php
/**
 * StockstradesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polygon API
 *
 * The future of fintech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * StockstradesApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StockstradesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'trades' => [
            'application/json',
        ],
        'v2TicksStocksTradesTickerDateGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation trades
     *
     * Trades
     *
     * @param  string $stock_ticker The ticker symbol to get trades for. (required)
     * @param  string $timestamp Query by trade timestamp. Either a date with the format YYYY-MM-DD or a nanosecond timestamp. (optional)
     * @param  string $timestamp_gte Range by timestamp. (optional)
     * @param  string $timestamp_gt Range by timestamp. (optional)
     * @param  string $timestamp_lte Range by timestamp. (optional)
     * @param  string $timestamp_lt Range by timestamp. (optional)
     * @param  string $order Order results based on the &#x60;sort&#x60; field. (optional, default to 'desc')
     * @param  int $limit Limit the number of results returned, default is 10 and max is 50000. (optional, default to 10)
     * @param  string $sort Sort field used for ordering. (optional, default to 'timestamp')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trades'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Trades200Response
     */
    public function trades($stock_ticker, $timestamp = null, $timestamp_gte = null, $timestamp_gt = null, $timestamp_lte = null, $timestamp_lt = null, $order = 'desc', $limit = 10, $sort = 'timestamp', string $contentType = self::contentTypes['trades'][0])
    {
        list($response) = $this->tradesWithHttpInfo($stock_ticker, $timestamp, $timestamp_gte, $timestamp_gt, $timestamp_lte, $timestamp_lt, $order, $limit, $sort, $contentType);
        return $response;
    }

    /**
     * Operation tradesWithHttpInfo
     *
     * Trades
     *
     * @param  string $stock_ticker The ticker symbol to get trades for. (required)
     * @param  string $timestamp Query by trade timestamp. Either a date with the format YYYY-MM-DD or a nanosecond timestamp. (optional)
     * @param  string $timestamp_gte Range by timestamp. (optional)
     * @param  string $timestamp_gt Range by timestamp. (optional)
     * @param  string $timestamp_lte Range by timestamp. (optional)
     * @param  string $timestamp_lt Range by timestamp. (optional)
     * @param  string $order Order results based on the &#x60;sort&#x60; field. (optional, default to 'desc')
     * @param  int $limit Limit the number of results returned, default is 10 and max is 50000. (optional, default to 10)
     * @param  string $sort Sort field used for ordering. (optional, default to 'timestamp')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trades'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Trades200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function tradesWithHttpInfo($stock_ticker, $timestamp = null, $timestamp_gte = null, $timestamp_gt = null, $timestamp_lte = null, $timestamp_lt = null, $order = 'desc', $limit = 10, $sort = 'timestamp', string $contentType = self::contentTypes['trades'][0])
    {
        $request = $this->tradesRequest($stock_ticker, $timestamp, $timestamp_gte, $timestamp_gt, $timestamp_lte, $timestamp_lt, $order, $limit, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Trades200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Trades200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Trades200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Trades200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Trades200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tradesAsync
     *
     * Trades
     *
     * @param  string $stock_ticker The ticker symbol to get trades for. (required)
     * @param  string $timestamp Query by trade timestamp. Either a date with the format YYYY-MM-DD or a nanosecond timestamp. (optional)
     * @param  string $timestamp_gte Range by timestamp. (optional)
     * @param  string $timestamp_gt Range by timestamp. (optional)
     * @param  string $timestamp_lte Range by timestamp. (optional)
     * @param  string $timestamp_lt Range by timestamp. (optional)
     * @param  string $order Order results based on the &#x60;sort&#x60; field. (optional, default to 'desc')
     * @param  int $limit Limit the number of results returned, default is 10 and max is 50000. (optional, default to 10)
     * @param  string $sort Sort field used for ordering. (optional, default to 'timestamp')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trades'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tradesAsync($stock_ticker, $timestamp = null, $timestamp_gte = null, $timestamp_gt = null, $timestamp_lte = null, $timestamp_lt = null, $order = 'desc', $limit = 10, $sort = 'timestamp', string $contentType = self::contentTypes['trades'][0])
    {
        return $this->tradesAsyncWithHttpInfo($stock_ticker, $timestamp, $timestamp_gte, $timestamp_gt, $timestamp_lte, $timestamp_lt, $order, $limit, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tradesAsyncWithHttpInfo
     *
     * Trades
     *
     * @param  string $stock_ticker The ticker symbol to get trades for. (required)
     * @param  string $timestamp Query by trade timestamp. Either a date with the format YYYY-MM-DD or a nanosecond timestamp. (optional)
     * @param  string $timestamp_gte Range by timestamp. (optional)
     * @param  string $timestamp_gt Range by timestamp. (optional)
     * @param  string $timestamp_lte Range by timestamp. (optional)
     * @param  string $timestamp_lt Range by timestamp. (optional)
     * @param  string $order Order results based on the &#x60;sort&#x60; field. (optional, default to 'desc')
     * @param  int $limit Limit the number of results returned, default is 10 and max is 50000. (optional, default to 10)
     * @param  string $sort Sort field used for ordering. (optional, default to 'timestamp')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trades'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tradesAsyncWithHttpInfo($stock_ticker, $timestamp = null, $timestamp_gte = null, $timestamp_gt = null, $timestamp_lte = null, $timestamp_lt = null, $order = 'desc', $limit = 10, $sort = 'timestamp', string $contentType = self::contentTypes['trades'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Trades200Response';
        $request = $this->tradesRequest($stock_ticker, $timestamp, $timestamp_gte, $timestamp_gt, $timestamp_lte, $timestamp_lt, $order, $limit, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'trades'
     *
     * @param  string $stock_ticker The ticker symbol to get trades for. (required)
     * @param  string $timestamp Query by trade timestamp. Either a date with the format YYYY-MM-DD or a nanosecond timestamp. (optional)
     * @param  string $timestamp_gte Range by timestamp. (optional)
     * @param  string $timestamp_gt Range by timestamp. (optional)
     * @param  string $timestamp_lte Range by timestamp. (optional)
     * @param  string $timestamp_lt Range by timestamp. (optional)
     * @param  string $order Order results based on the &#x60;sort&#x60; field. (optional, default to 'desc')
     * @param  int $limit Limit the number of results returned, default is 10 and max is 50000. (optional, default to 10)
     * @param  string $sort Sort field used for ordering. (optional, default to 'timestamp')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['trades'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tradesRequest($stock_ticker, $timestamp = null, $timestamp_gte = null, $timestamp_gt = null, $timestamp_lte = null, $timestamp_lt = null, $order = 'desc', $limit = 10, $sort = 'timestamp', string $contentType = self::contentTypes['trades'][0])
    {

        // verify the required parameter 'stock_ticker' is set
        if ($stock_ticker === null || (is_array($stock_ticker) && count($stock_ticker) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stock_ticker when calling trades'
            );
        }







        if ($limit !== null && $limit > 50000) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling StockstradesApi.trades, must be smaller than or equal to 50000.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling StockstradesApi.trades, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v3/trades/{stockTicker}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp,
            'timestamp', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp_gte,
            'timestamp.gte', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp_gt,
            'timestamp.gt', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp_lte,
            'timestamp.lte', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp_lt,
            'timestamp.lt', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($stock_ticker !== null) {
            $resourcePath = str_replace(
                '{' . 'stockTicker' . '}',
                ObjectSerializer::toPathValue($stock_ticker),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/csv', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apiKey');
        if ($apiKey !== null) {
            $queryParams['apiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v2TicksStocksTradesTickerDateGet
     *
     * Trades
     *
     * @param  string $ticker The ticker symbol we want trades for. (required)
     * @param  \DateTime $date The date/day of the trades to retrieve in the format YYYY-MM-DD. (required)
     * @param  int $timestamp The timestamp offset, used for pagination. This is the offset at which to start the results. Using the &#x60;timestamp&#x60; of the last result as the offset will give you the next page of results. (optional)
     * @param  int $timestamp_limit The maximum timestamp allowed in the results. (optional)
     * @param  bool $reverse Reverse the order of the results. (optional)
     * @param  int $limit Limit the size of the response, max 50000 and default 5000. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v2TicksStocksTradesTickerDateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response
     */
    public function v2TicksStocksTradesTickerDateGet($ticker, $date, $timestamp = null, $timestamp_limit = null, $reverse = null, $limit = null, string $contentType = self::contentTypes['v2TicksStocksTradesTickerDateGet'][0])
    {
        list($response) = $this->v2TicksStocksTradesTickerDateGetWithHttpInfo($ticker, $date, $timestamp, $timestamp_limit, $reverse, $limit, $contentType);
        return $response;
    }

    /**
     * Operation v2TicksStocksTradesTickerDateGetWithHttpInfo
     *
     * Trades
     *
     * @param  string $ticker The ticker symbol we want trades for. (required)
     * @param  \DateTime $date The date/day of the trades to retrieve in the format YYYY-MM-DD. (required)
     * @param  int $timestamp The timestamp offset, used for pagination. This is the offset at which to start the results. Using the &#x60;timestamp&#x60; of the last result as the offset will give you the next page of results. (optional)
     * @param  int $timestamp_limit The maximum timestamp allowed in the results. (optional)
     * @param  bool $reverse Reverse the order of the results. (optional)
     * @param  int $limit Limit the size of the response, max 50000 and default 5000. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v2TicksStocksTradesTickerDateGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function v2TicksStocksTradesTickerDateGetWithHttpInfo($ticker, $date, $timestamp = null, $timestamp_limit = null, $reverse = null, $limit = null, string $contentType = self::contentTypes['v2TicksStocksTradesTickerDateGet'][0])
    {
        $request = $this->v2TicksStocksTradesTickerDateGetRequest($ticker, $date, $timestamp, $timestamp_limit, $reverse, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v2TicksStocksTradesTickerDateGetAsync
     *
     * Trades
     *
     * @param  string $ticker The ticker symbol we want trades for. (required)
     * @param  \DateTime $date The date/day of the trades to retrieve in the format YYYY-MM-DD. (required)
     * @param  int $timestamp The timestamp offset, used for pagination. This is the offset at which to start the results. Using the &#x60;timestamp&#x60; of the last result as the offset will give you the next page of results. (optional)
     * @param  int $timestamp_limit The maximum timestamp allowed in the results. (optional)
     * @param  bool $reverse Reverse the order of the results. (optional)
     * @param  int $limit Limit the size of the response, max 50000 and default 5000. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v2TicksStocksTradesTickerDateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v2TicksStocksTradesTickerDateGetAsync($ticker, $date, $timestamp = null, $timestamp_limit = null, $reverse = null, $limit = null, string $contentType = self::contentTypes['v2TicksStocksTradesTickerDateGet'][0])
    {
        return $this->v2TicksStocksTradesTickerDateGetAsyncWithHttpInfo($ticker, $date, $timestamp, $timestamp_limit, $reverse, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v2TicksStocksTradesTickerDateGetAsyncWithHttpInfo
     *
     * Trades
     *
     * @param  string $ticker The ticker symbol we want trades for. (required)
     * @param  \DateTime $date The date/day of the trades to retrieve in the format YYYY-MM-DD. (required)
     * @param  int $timestamp The timestamp offset, used for pagination. This is the offset at which to start the results. Using the &#x60;timestamp&#x60; of the last result as the offset will give you the next page of results. (optional)
     * @param  int $timestamp_limit The maximum timestamp allowed in the results. (optional)
     * @param  bool $reverse Reverse the order of the results. (optional)
     * @param  int $limit Limit the size of the response, max 50000 and default 5000. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v2TicksStocksTradesTickerDateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v2TicksStocksTradesTickerDateGetAsyncWithHttpInfo($ticker, $date, $timestamp = null, $timestamp_limit = null, $reverse = null, $limit = null, string $contentType = self::contentTypes['v2TicksStocksTradesTickerDateGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\V2TicksStocksTradesTickerDateGet200Response';
        $request = $this->v2TicksStocksTradesTickerDateGetRequest($ticker, $date, $timestamp, $timestamp_limit, $reverse, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v2TicksStocksTradesTickerDateGet'
     *
     * @param  string $ticker The ticker symbol we want trades for. (required)
     * @param  \DateTime $date The date/day of the trades to retrieve in the format YYYY-MM-DD. (required)
     * @param  int $timestamp The timestamp offset, used for pagination. This is the offset at which to start the results. Using the &#x60;timestamp&#x60; of the last result as the offset will give you the next page of results. (optional)
     * @param  int $timestamp_limit The maximum timestamp allowed in the results. (optional)
     * @param  bool $reverse Reverse the order of the results. (optional)
     * @param  int $limit Limit the size of the response, max 50000 and default 5000. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v2TicksStocksTradesTickerDateGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v2TicksStocksTradesTickerDateGetRequest($ticker, $date, $timestamp = null, $timestamp_limit = null, $reverse = null, $limit = null, string $contentType = self::contentTypes['v2TicksStocksTradesTickerDateGet'][0])
    {

        // verify the required parameter 'ticker' is set
        if ($ticker === null || (is_array($ticker) && count($ticker) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ticker when calling v2TicksStocksTradesTickerDateGet'
            );
        }

        // verify the required parameter 'date' is set
        if ($date === null || (is_array($date) && count($date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $date when calling v2TicksStocksTradesTickerDateGet'
            );
        }






        $resourcePath = '/v2/ticks/stocks/trades/{ticker}/{date}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp,
            'timestamp', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestamp_limit,
            'timestampLimit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reverse,
            'reverse', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($ticker !== null) {
            $resourcePath = str_replace(
                '{' . 'ticker' . '}',
                ObjectSerializer::toPathValue($ticker),
                $resourcePath
            );
        }
        // path params
        if ($date !== null) {
            $resourcePath = str_replace(
                '{' . 'date' . '}',
                ObjectSerializer::toPathValue($date),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apiKey');
        if ($apiKey !== null) {
            $queryParams['apiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
