#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$client = new PolygonIO\PolygonIO('API_KEY');

$client->websockets->crypto->connect(
    'C.USD',
    function($data) {
        var_dump($data);
    }
);
