<?php
/**
 * RatingSection
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polygon API
 *
 * The future of fintech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RatingSection Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RatingSection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RatingSection';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'current' => 'float',
        'month1' => 'float',
        'month2' => 'float',
        'month3' => 'float',
        'month4' => 'float',
        'month5' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'current' => null,
        'month1' => null,
        'month2' => null,
        'month3' => null,
        'month4' => null,
        'month5' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'current' => false,
        'month1' => false,
        'month2' => false,
        'month3' => false,
        'month4' => false,
        'month5' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current' => 'current',
        'month1' => 'month1',
        'month2' => 'month2',
        'month3' => 'month3',
        'month4' => 'month4',
        'month5' => 'month5'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current' => 'setCurrent',
        'month1' => 'setMonth1',
        'month2' => 'setMonth2',
        'month3' => 'setMonth3',
        'month4' => 'setMonth4',
        'month5' => 'setMonth5'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current' => 'getCurrent',
        'month1' => 'getMonth1',
        'month2' => 'getMonth2',
        'month3' => 'getMonth3',
        'month4' => 'getMonth4',
        'month5' => 'getMonth5'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('current', $data ?? [], null);
        $this->setIfExists('month1', $data ?? [], null);
        $this->setIfExists('month2', $data ?? [], null);
        $this->setIfExists('month3', $data ?? [], null);
        $this->setIfExists('month4', $data ?? [], null);
        $this->setIfExists('month5', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['current'] === null) {
            $invalidProperties[] = "'current' can't be null";
        }
        if ($this->container['month1'] === null) {
            $invalidProperties[] = "'month1' can't be null";
        }
        if ($this->container['month2'] === null) {
            $invalidProperties[] = "'month2' can't be null";
        }
        if ($this->container['month3'] === null) {
            $invalidProperties[] = "'month3' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current
     *
     * @return float
     */
    public function getCurrent()
    {
        return $this->container['current'];
    }

    /**
     * Sets current
     *
     * @param float $current Analyst Rating at current month
     *
     * @return self
     */
    public function setCurrent($current)
    {
        if (is_null($current)) {
            throw new \InvalidArgumentException('non-nullable current cannot be null');
        }
        $this->container['current'] = $current;

        return $this;
    }

    /**
     * Gets month1
     *
     * @return float
     */
    public function getMonth1()
    {
        return $this->container['month1'];
    }

    /**
     * Sets month1
     *
     * @param float $month1 Analyst Ratings at 1 month in the future
     *
     * @return self
     */
    public function setMonth1($month1)
    {
        if (is_null($month1)) {
            throw new \InvalidArgumentException('non-nullable month1 cannot be null');
        }
        $this->container['month1'] = $month1;

        return $this;
    }

    /**
     * Gets month2
     *
     * @return float
     */
    public function getMonth2()
    {
        return $this->container['month2'];
    }

    /**
     * Sets month2
     *
     * @param float $month2 Analyst Ratings at 2 month in the future
     *
     * @return self
     */
    public function setMonth2($month2)
    {
        if (is_null($month2)) {
            throw new \InvalidArgumentException('non-nullable month2 cannot be null');
        }
        $this->container['month2'] = $month2;

        return $this;
    }

    /**
     * Gets month3
     *
     * @return float
     */
    public function getMonth3()
    {
        return $this->container['month3'];
    }

    /**
     * Sets month3
     *
     * @param float $month3 Analyst Ratings at 3 month in the future
     *
     * @return self
     */
    public function setMonth3($month3)
    {
        if (is_null($month3)) {
            throw new \InvalidArgumentException('non-nullable month3 cannot be null');
        }
        $this->container['month3'] = $month3;

        return $this;
    }

    /**
     * Gets month4
     *
     * @return float|null
     */
    public function getMonth4()
    {
        return $this->container['month4'];
    }

    /**
     * Sets month4
     *
     * @param float|null $month4 Analyst Ratings at 4 month in the future
     *
     * @return self
     */
    public function setMonth4($month4)
    {
        if (is_null($month4)) {
            throw new \InvalidArgumentException('non-nullable month4 cannot be null');
        }
        $this->container['month4'] = $month4;

        return $this;
    }

    /**
     * Gets month5
     *
     * @return float|null
     */
    public function getMonth5()
    {
        return $this->container['month5'];
    }

    /**
     * Sets month5
     *
     * @param float|null $month5 Analyst Ratings at 5 month in the future
     *
     * @return self
     */
    public function setMonth5($month5)
    {
        if (is_null($month5)) {
            throw new \InvalidArgumentException('non-nullable month5 cannot be null');
        }
        $this->container['month5'] = $month5;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


