<?php
/**
 * ListConditions200ResponseResultsInnerUpdateRulesConsolidatedTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polygon API
 *
 * The future of fintech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListConditions200ResponseResultsInnerUpdateRulesConsolidatedTest Class Doc Comment
 *
 * @category    Class
 * @description Describes aggregation rules on a consolidated (all exchanges) basis.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListConditions200ResponseResultsInnerUpdateRulesConsolidatedTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListConditions200ResponseResultsInnerUpdateRulesConsolidated"
     */
    public function testListConditions200ResponseResultsInnerUpdateRulesConsolidated()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "updates_high_low"
     */
    public function testPropertyUpdatesHighLow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "updates_open_close"
     */
    public function testPropertyUpdatesOpenClose()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "updates_volume"
     */
    public function testPropertyUpdatesVolume()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
