<?php
/**
 * V2TicksStocksNbboTickerDateGet200ResponseAllOfResultsInnerAllOfXTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polygon API
 *
 * The future of fintech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V2TicksStocksNbboTickerDateGet200ResponseAllOfResultsInnerAllOfXTest Class Doc Comment
 *
 * @category    Class
 * @description V2TicksStocksNbboTickerDateGet200ResponseAllOfResultsInnerAllOfX
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V2TicksStocksNbboTickerDateGet200ResponseAllOfResultsInnerAllOfXTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V2TicksStocksNbboTickerDateGet200ResponseAllOfResultsInnerAllOfX"
     */
    public function testV2TicksStocksNbboTickerDateGet200ResponseAllOfResultsInnerAllOfX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
