<?php
/**
 * CryptoaggregatesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polygon API
 *
 * The future of fintech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CryptoaggregatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CryptoaggregatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cryptoMACD
     *
     * Moving Average Convergence/Divergence (MACD).
     *
     */
    public function testCryptoMACD()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2AggsGroupedLocaleGlobalMarketCryptoDateGet
     *
     * Grouped Daily (Bars).
     *
     */
    public function testV2AggsGroupedLocaleGlobalMarketCryptoDateGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2AggsTickerCryptoTickerPrevGet
     *
     * Previous Close.
     *
     */
    public function testV2AggsTickerCryptoTickerPrevGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2AggsTickerCryptoTickerRangeMultiplierTimespanFromToGet
     *
     * Aggregates (Bars).
     *
     */
    public function testV2AggsTickerCryptoTickerRangeMultiplierTimespanFromToGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
