<?php
/**
 * FxaggregatesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polygon API
 *
 * The future of fintech.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FxaggregatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FxaggregatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for forexEMA
     *
     * Exponential Moving Average (EMA).
     *
     */
    public function testForexEMA()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forexMACD
     *
     * Moving Average Convergence/Divergence (MACD).
     *
     */
    public function testForexMACD()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forexRSI
     *
     * Relative Strength Index (RSI).
     *
     */
    public function testForexRSI()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forexSMA
     *
     * Simple Moving Average (SMA).
     *
     */
    public function testForexSMA()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2AggsGroupedLocaleGlobalMarketFxDateGet
     *
     * Grouped Daily (Bars).
     *
     */
    public function testV2AggsGroupedLocaleGlobalMarketFxDateGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2AggsTickerForexTickerPrevGet
     *
     * Previous Close.
     *
     */
    public function testV2AggsTickerForexTickerPrevGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v2AggsTickerForexTickerRangeMultiplierTimespanFromToGet
     *
     * Aggregates (Bars).
     *
     */
    public function testV2AggsTickerForexTickerRangeMultiplierTimespanFromToGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
